version: "3.3"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Kong: The API Gateway
  #######################################
  kong-gateway-dbless:
    container_name: kong-gateway-dbless
    image: kong/kong-gateway:3.0.1.0
    #restart: always
    networks:
      - kong-net
    volumes:
      - "./config:/usr/local/kong/declarative"
      - "./logs/file.log:/file.log"
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
      # KONG_LOG_LEVEL: debug
      # KONG_PLUGINS: bundled
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - "4443:8443"
      - "4444:8444"
      - "4000:8000"
      - "4001:8001"
      - "4002:8002"
      - "4003:8003"



# services:
#   kong:
#     image: kong
#     volumes:
#       - "./config:/usr/local/kong/declarative"
#       - "./logs/file.log:/file.log"
#     environment:
#       - KONG_DATABASE=off
#       - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
#       - KONG_PROXY_ACCESS_LOG=/dev/stdout
#       - KONG_ADMIN_ACCESS_LOG=/dev/stdout
#       - KONG_PROXY_ERROR_LOG=/dev/stderr
#       - KONG_ADMIN_ERROR_LOG=/dev/stderr
#       - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
#       - KONG_LOG_LEVEL=debug
#       - KONG_PLUGINS=bundled
#     ports:
#       - "8000:8000/tcp"
#       - "127.0.0.1:7990:8001/tcp"
#       - "8001:8001/tcp"
#       - "8443:8443/tcp"
#       - "127.0.0.1:8444:8444/tcp"