_format_version: "2.1"


services:
- name: my-api-server
  url: https://feedback-social.com

# http://localhost:4000
routes:
- name: api-requests
  service: my-api-server
  paths:
    - /

## for jwt auth
##http://localhost:4001/consumers/login-server/jwt
# plugins:
# - name: jwt
#   service: my-api-server
#   enabled: true
#   config:
#     key_claim_name: kid
#     claims_to_verify:
#     - exp

# consumers:
#   - username: login-server

# jwt_secrets:
#   - consumer: login-server
#     secret: "1234"
