version: "3"

networks:
 kong-net:
  driver: bridge

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    container_name: kong-database
    image:  postgres:9.6
    #restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5431:5432"

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    container_name: kong-migrations
    image: kong/kong-gateway:3.0.1.0
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    #restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PG_PORT: 5431
      KONG_PASSWORD: test
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    container_name: kong-gateway
    image: kong/kong-gateway:3.0.1.0
    #restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PORT: 5431
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    depends_on:
      - kong-migration
      - kong-database
    ports:
      - "8443:8443"
      - "8444:8444"
      - "8004:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"


  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:next
    command: "-c prepare -a postgres -u postgresql://kong:kongpass@kong-database:5431/kong"
    networks:
      - kong-net
    #restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:next
    #restart: always
    networks:
        - kong-net
    environment:
      DB_ADAPTER: postgres
      DB_PASSWORD: kongpass
      DB_HOST: kong-database
      DB_PORT: 5431
      DB_USER: kong
      TOKEN_SECRET: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      DB_DATABASE: kong
      NODE_ENV: production
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
